# choose language file (default = english.yml)
language-file: "english.yml"

#Enable or disable commands/modules here:
commands:
  ping: true
  servers: true
  online: true
  uuid: true
  friends: true
  report: true
  lookup: true
  global: true

#Global connection messages
connection-messages:
  bungee: true #announce on join of server (X joined the network/left the network)
  serverswitch: true #announce server switch (X switched servers from X to Y)
  friends: true #announce to players their friend joined or left

#Add /<alias> shortcuts to connect a bungeecord server.
server_shortcuts: {}
#  examplebungeeserver: #bungeecoord server here
#      aliases: #list of aliases to use to connect to server
#        - exampleshortcut
#      permissions: true #should there be permissions to connect?

#reporting configuration
report:
  use_reason_list: true #should players use a predefined list of reasons, or enter reason manually?
  reasons:
    - Griefing
    - Harassment
    - Hacking


# should /servers show restricted servers (with [restricted] text)
show_restricted_servers: false

# do not edit, used for version check:
config-version: 1.0